# Synchornize with go requirements
# https://github.com/conda-forge/go-feedstock/blob/main/recipe/conda_build_config.yaml
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - '10.14'                # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - '10.14'                # [osx and x86_64]

# 4.23.4 is the latest protobuf migration
# 3.21 is the version that tensorflow 2.13 was last built with
libprotobuf:
- '4.24.3'
- '3.21'

libgrpc:
- '1.58'
- '1.51'
