# Synchornize with go requirements
# https://github.com/conda-forge/go-feedstock/blob/main/recipe/conda_build_config.yaml
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - '10.14'                # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - '10.14'                # [osx and x86_64]
c_compiler_version:        # [osx]
  - 14                     # [osx]
cxx_compiler_version:      # [osx]
  - 14                     # [osx]
c_compiler_version:        # [linux]
  - 11                     # [linux]
cxx_compiler_version:      # [linux]
  - 11                     # [linux]
