{% set name = "zaber-motion" %}
{% set version = "4.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/zaber-core-libs/zaber-motion-lib/-/archive/v{{ version }}/zaber-motion-lib-v{{ version }}.tar.gz
  sha256: 34926d8221e6bd6290955a173082c8d1712380a5c04f2bbe4af13ccdf4229dd9
  folder: src/zaber-motion
  patches:
    - no_bindings_install.patch

build:
  number: 2

outputs:
  - name: libzaber-motion
    script: build_lib.sh   # [unix]
    script: build_lib.bat  # [win]
    run_exports:
      - {{ pin_subpackage('libzaber-motion', 'x.x') }}

    requirements:
      build:
        - {{ compiler('cgo') }}
        - {{ compiler('m2w64_c') }}    # [win]
        - {{ compiler('m2w64_cxx') }}  # [win]
        - {{ compiler('c') }}          # [not win]
        - {{ compiler('cxx') }}        # [not win]
        - sysroot_linux-64 2.17        # [linux64]
        - protoc-gen-go
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - libprotobuf                            # [build_platform != target_platform]
      host:
        - python
        - pip
        - libprotobuf
        - protobuf
        - mypy-protobuf
      run:
        - python
        - protobuf
        - rx
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

    test:
      commands:
        - test -f ${PREFIX}/lib/zaber-motion-lib${SHLIB_EXT}  # [unix]

  - name: zaber-motion
    script: build_python.sh   # [unix]
    script: build_python.bat  # [win]
    build:
      noarch: python

    requirements:
      build:
        - protoc-gen-go
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - libprotobuf                            # [build_platform != target_platform]
      host:
        - python
        - pip
        - libprotobuf
        - protobuf
        - mypy-protobuf
      run:
        - python
        - protobuf
        - rx
        - {{ pin_subpackage('libzaber-motion', 'x.x.x') }} 
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - zaber_motion

about:
  home: https://gitlab.com/zaber-core-libs/zaber-motion-lib
  license: MIT
  license_family: MIT
  license_file:
    - src/zaber-motion/LICENSE
    - LICENSE_GO_MODULES
  summary: A Python library used to operate Zaber devices.
  doc_url: https://www.zaber.com/software/docs/motion-library/
  dev_url: https://gitlab.com/zaber-core-libs/zaber-motion-lib

extra:
  recipe-maintainers:
    - hmaarrfk
