{% set name = "zaber-motion" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/zaber-core-libs/zaber-motion-lib/-/archive/v{{ version }}/zaber-motion-lib-v{{ version }}.tar.gz
  sha256: df541beaa03a71bf6205e2c3a6000ebef944c8a69e3909f2bf5c06d79c57c283
  folder: src/zaber-motion
  patches:
    - no_bindings_install.patch
    - dont_specify_python_3_in_executable_name.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('cgo') }}
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('cxx') }}        # [not win]
  host:
    - python
    - pip
    - libprotobuf
    - protobuf
    - protoc-gen-go
    - mypy-protobuf  1
  run:
    - python
    - protobuf
    - rx

test:
  imports:
    - zaber_motion

about:
  home: https://gitlab.com/zaber-core-libs/zaber-motion-lib
  license: MIT
  license_family: MIT
  license_file:
    - src/zaber-motion/LICENSE
    - LICENSE_GO_MODULES
  summary: A Python library used to operate Zaber devices.
  doc_url: https://www.zaber.com/software/docs/motion-library/
  dev_url: https://gitlab.com/zaber-core-libs/zaber-motion-lib

extra:
  recipe-maintainers:
    - hmaarrfk
