{% set version = "5.2.0" %}

package:
  name: zaber-motion-split
  version: {{ version }}

source:
  url: https://gitlab.com/zaber-core-libs/zaber-motion-lib/-/archive/v{{ version }}/zaber-motion-lib-v{{ version }}.tar.gz
  sha256: 2e16b1356813ed724d208202a2175171ac60b044662e43099ea9e5997d8e646e
  folder: src/zaber-motion
  patches:
    - no_bindings_install.patch

build:
  number: 0

outputs:
  - name: libzaber-motion
    script: build_lib.sh  # [unix]
    script: bld_lib.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('libzaber-motion', 'x.x') }}

    requirements:
      build:
        - protoc-gen-go
        - {{ compiler('cgo') }}
        - {{ compiler('m2w64_c') }}    # [win]
        - {{ compiler('m2w64_cxx') }}  # [win]
        - {{ compiler('c') }}          # [not win]
        - {{ compiler('cxx') }}        # [not win]
        - sysroot_linux-64 2.17        # [linux64]
        - libprotobuf                  # [build_platform != target_platform]
      host:
        - libprotobuf
      run:
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

    test:
      commands:
        - test -f ${PREFIX}/lib/zaber-motion-lib${SHLIB_EXT}  # [unix]

  - name: zaber-motion
    script: build_python.sh  # [unix]
    script: bld_python.bat  # [win]
    build:
      noarch: python

    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - libprotobuf                            # [build_platform != target_platform]
      host:
        - python >=3.8
        - pip
        - libprotobuf
        - protobuf
        - mypy-protobuf
      run:
        - python >=3.8
        - protobuf
        - rx
        - {{ pin_subpackage('libzaber-motion', exact=True) }}

    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - zaber_motion

about:
  home: https://gitlab.com/zaber-core-libs/zaber-motion-lib
  license: MIT
  license_family: MIT
  license_file:
    - src/zaber-motion/LICENSE
    - LICENSE_GO_MODULES
  summary: A Python library used to operate Zaber devices.
  doc_url: https://www.zaber.com/software/docs/motion-library/
  dev_url: https://gitlab.com/zaber-core-libs/zaber-motion-lib

extra:
  recipe-maintainers:
    - hmaarrfk
