build_platform:
  osx_arm64: osx_64
provider:
  linux_aarch64: default
  linux_ppc64le: default
conda_forge_output_validation: true
test: native_and_emulated
github:
  branch_name: main
  tooling_branch_name: main
